### ISSUE TITLE
How to set nodejs4.3

### ISSUE THREAD

**Issue by omnius45467** [cameronhunter/generator-alexa-skill#29]
AWS Lambda is suggesting nodejs version 4.3, how can I set this in the skill prior to deploy?

**Comment by ghost** [comment]
See https://github.com/axis-tip/alexa-skill-meezan/blob/master/.travis.yml

Basically, I believe you have to do something like:

``` json
deploy:
  provider: lambda
  function_name: (your function name)
  role: (your role name)
  handler_name: handler
  runtime: nodejs4.3
  zip: build/package.zip
  access_key_id: (your access key)
  secret_access_key:
    secure: (your encrypted deploy key)
```

**Comment by tjaffri** [comment]
@cameronhunter this can probably be closed, since I think I answered it correctly (I have this working for my skill).

If you want a PR to the .travis.yml to close this please let me know.
