### ISSUE TITLE
Debugging / Telemetry guidance

### ISSUE THREAD

**Issue by tjaffri** [cameronhunter/generator-alexa-skill#36]
I was wondering if you had any guidance on how to debug a skill generated this way. I am reduced to two methods at this point:
1. Write lots of tests (a good thing) and if something breaks use console.log to figure it out (a bad thing). I can't attach a debugger since it cannot resolve the sourcemaps generated by webpack (I use vscode on a Mac)
2. Use the CloudWatch logs to figure out why something failed when the skill is running on my echo. Since I'm the only person using it for now this works ok since something fails and I glance at my watch to note the time... then correlate the timestamp in the log later. But this won't scale if I have more people using it once I publish. Would be great to have guidance on how to integrate with a telemetry / crash logs service like google analytics, raygun.io, or whatever else people use nowadays to see what the top issues are and then act on them.

I was wondering if you had any guidance on the above. The first one is more pressing but I figure both are related.

Thanks.

**Comment by tjaffri** [comment]
@cameronhunter any thoughts on this? I hope you have some learnings to share in this space since you have published skills that use this generator. Thank you!

**Comment by cameronhunter** [comment]
I haven't needed to debug any of my (admittedly simple) skills yet. I often write tests to cover edge cases or issues uncovered with manual testing. You could use [aws-lambda-local](https://github.com/Max-Kolodezniy/aws-lambda-local) to manually test your skill without needing to deploy, but I don't see much benefit over writing a test.

With regards to error tracking, your intent handlers can return a `Promise` which you could add a `catch` handler and perform any error logging you want, as well as providing a helpful response to the user.
